### PR TITLE
publisher Update

### PR DESCRIPTION
**Pull request by steveoni**
This pull request merge publisher update into gift-portal and also implement the issue listed here https://github.com/datopian/gift-publisher/issues/42

### CODE REVIEW

**Comment by risenW** [comment]
@steveoni Cypress is failing as well:

```bash

> Build error occurred
ReferenceError: navigator is not defined
    at /home/runner/work/gift-portal/gift-portal/node_modules/giftpub/node_modules/@yaireo/tagify/dist/tagify.min.js:1:1972
    at /home/runner/work/gift-portal/gift-portal/node_modules/giftpub/node_modules/@yaireo/tagify/dist/tagify.min.js:1:84
    at Object.<anonymous> (/home/runner/work/gift-portal/gift-portal/node_modules/giftpub/node_modules/@yaireo/tagify/dist/tagify.min.js:1:159)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /home/runner/work/gift-portal/gift-portal/node_modules/giftpub/node_modules/@yaireo/tagify/dist/react.tagify.js:1:990 {
  type: 'ReferenceError'
}
```

**Comment by steveoni** [comment]
> @steveoni Cypress and vercel are failing with the same error shown below:
> 
> ```shell
> > Build error occurred
> ReferenceError: navigator is not defined
>     at /home/runner/work/gift-portal/gift-portal/node_modules/giftpub/node_modules/@yaireo/tagify/dist/tagify.min.js:1:1972
>     at /home/runner/work/gift-portal/gift-portal/node_modules/giftpub/node_modules/@yaireo/tagify/dist/tagify.min.js:1:84
>     at Object.<anonymous> (/home/runner/work/gift-portal/gift-portal/node_modules/giftpub/node_modules/@yaireo/tagify/dist/tagify.min.js:1:159)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at /home/runner/work/gift-portal/gift-portal/node_modules/giftpub/node_modules/@yaireo/tagify/dist/react.tagify.js:1:990 {
>   type: 'ReferenceError'
> }
> ```

yeah, I experienced this error in development and thought I solve it using dynamic loading.

the error is caused by the @yeiro package you added to the publisher app

**Comment by risenW** [comment]
@steveoni are you still working on this pull?

**Comment by steveoni** [comment]
no. this was the pull request that we were using @yeiro in publisher. I will close it with this comment

**Pull request closed without merging**
