### PR TITLE
Using apollo for state management

### LINKED ISSUE #75: Introducing apollo for state management and using it to power the MetaStore
We want a seamless way of dealing with the cache and global states in Gift-portal. We want to be able to retrieve cached data easily as well as update datasets that are out of date.

## Acceptance

* [x] There is a MetaStore class with the following API **Done** https://github.com/datopian/gift-portal/blob/master/lib/Metastore.js
  * [x] MetaStore.fetch()  **Done** https://github.com/datopian/gift-portal/blob/26029e86f70cb23ba802bddcf3219a17867149e6/lib/Metastore.js#L38
  * [x] MetaStore.create **Done** https://github.com/datopian/gift-portal/blob/26029e86f70cb23ba802bddcf3219a17867149e6/lib/Metastore.js#L54
  * [x] MetaStore.update **Done** https://github.com/datopian/gift-portal/blob/26029e86f70cb23ba802bddcf3219a17867149e6/lib/Metastore.js#L78
  * [x] MetaStore.search('') => for now this can return "all" datasets if no query string **Done** https://github.com/datopian/gift-portal/blob/26029e86f70cb23ba802bddcf3219a17867149e6/lib/Metastore.js#L21
  * [ ] Future: MetaStore.delete
* [x] I have set up apollo for local state management **Done** https://github.com/datopian/gift-portal/blob/master/lib/apolloClient.js
* [x] MetaStore uses apollo as proxy for queries and for caching  **Done* https://github.com/datopian/gift-portal/blob/26029e86f70cb23ba802bddcf3219a17867149e6/lib/Metastore.js#L18
* [x] On app boot, I pre-populate the store based on all datasets in a github org **Done** https://github.com/datopian/gift-portal/blob/26029e86f70cb23ba802bddcf3219a17867149e6/pages/index.js#L60

## Task

* [x] Introduce apollo for local state management
* [x] Wire up MetaStore to use apollo local state
* [x] Refactor app boot code that loads metastore to ...
  * [x] Use metastore-lib-js
  * [x] Store this in apollo
  * [x] Wire up apollo local store to use metastore-lib-js to do the action
  * [x] fetch: retrieve if it doesn't have the value already

### Analysis

See detailed analysis and why we recommended using Apollo in this issue #72 

### More Analysis

* Dataset fetched from github + datapackage.json via MetaStore.fetch
* Two options
  * `datapackage.json` exists in github => use that as descriptor
    * Add githubId if not present when we do the fetch (FUTURE: maybe we can assume this is always there ...)
  * does not exist => create a minimal descriptor with name and githubId and empty resources array

What does a Dataset descriptor look like for these datasets

```
{
  // minimum info
  name: "presepuseto-mexico",
  id: "github repo id"  // (unique i hope?) Thadeu: node id
  
  // much more ... 
}
```

// on app boot we still pre-load the "state" cache like we do currently but put it
// into apollo ...
```
MetaStore.fetch
  => look in apollo ...
  => apollo will return if already has it ...
  => o/w apollo will use metastore-lib-js to load and then return
```

### PR DESCRIPTION
**Pull request by risenW**
This pull fixes #75

### CODE REVIEW

**Review by steveoni — APPROVED** [review]
LGTM!

**Comment by steveoni** [comment]
The deployment is failing do you know why?

**Comment by steveoni** [comment]
i can't even view `vercel/datopian1` it is showing `404`

**Comment by risenW** [comment]
> The deployment is failing do you know why?

Probably the env key since its not master. Seeing this in vercel:

Screen Shot 2021-02-01 at 1 37 19 PM

**Comment by steveoni** [comment]
can you try checking `vercel/datopian1` is showing 404 here

**Comment by risenW** [comment]
> can you try checking `vercel/datopian1` is showing 404 here

I can access it from here

**Comment by steveoni** [comment]
maybe i'm not a member again

**Comment by steveoni** [comment]
That means you can change the environment variables then

**Pull request merged**
